import React from 'react';
import Footer from '@/components/footer/page';

const PrivacyPolicy = () => {
  return (
    <>
    <div className="max-w-5xl mx-auto px-4 py-8">
      <h1 className="text-3xl font-bold mb-4">Privacy Policy</h1>
      <p className="text-sm text-gray-500 mb-8">Last updated: August 08, 2024</p>
      <p className="mb-4">
        This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
      </p>
      <p className="mb-4">
        We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been created with the help of the 
        <a href="https://www.termsfeed.com/privacy-policy-generator/" target="_blank" className="text-blue-500 hover:underline">Privacy Policy Generator</a>.
      </p>

      <h2 className="text-2xl font-semibold mt-8 mb-4">Interpretation and Definitions</h2>

      <h3 className="text-xl font-semibold mt-6 mb-4">Interpretation</h3>
      <p className="mb-4">
        The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
      </p>

      <h3 className="text-xl font-semibold mt-6 mb-4">Definitions</h3>
      <p className="mb-4">For the purposes of this Privacy Policy:</p>
      <ul className="list-disc list-inside mb-4">
        <li className="mb-2">
          <strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.
        </li>
        <li className="mb-2">
          <strong>Affiliate</strong> means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.
        </li>
        <li className="mb-2">
          <strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to PulseZest, 69/2, Jagatpur Road, Pashupati vihar colony, Bareilly, Uttar Pradesh, 243006.
        </li>
        <li className="mb-2">
          <strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.
        </li>
        <li className="mb-2">
          <strong>Country</strong> refers to: Uttar Pradesh, India.
        </li>
        <li className="mb-2">
          <strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.
        </li>
        <li className="mb-2">
          <strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.
        </li>
        <li className="mb-2">
          <strong>Service</strong> refers to the Website.
        </li>
        <li className="mb-2">
          <strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.
        </li>
        <li className="mb-2">
          <strong>Third-party Social Media Service</strong> refers to any website or any social network website through which a User can log in or create an account to use the Service.
        </li>
        <li className="mb-2">
          <strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).
        </li>
        <li className="mb-2">
          <strong>Website</strong> refers to PulseZest Learning, accessible from 
          <a href="https://learning.pulsezest.com" className="text-blue-500 hover:underline">https://learning.pulsezest.com</a>.
        </li>
        <li className="mb-2">
          <strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.
        </li>
      </ul>

      {/* Add more sections of your Privacy Policy here using similar Tailwind classes */}
      
      <h2 className="text-2xl font-semibold mt-8 mb-4">Contact Us</h2>
      <p className="mb-4">If you have any questions about this Privacy Policy, You can contact us:</p>
      <ul className="list-disc list-inside mb-4">
        <li className="mb-2">By email: contact@pulsezest.com</li>
        <li className="mb-2">By phone number: 7248457558</li>
        <li className="mb-2">By mail: 69/2, Jagatpur Road, Pashupati vihar colony, Bareilly, Uttar Pradesh, 243006</li>
      </ul>

      
    </div>
    <Footer/>
    </>
  );
};

export default PrivacyPolicy;
